[package]
name = "tbh-core"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true }
tbh-capture.workspace = true
tbh-input.workspace = true
tbh-vision.workspace = true
thiserror.workspace = true
toml.workspace = true
tracing.workspace = true

[lints]
workspace = true
