[package]
name = "tbh-cli"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "tbh"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
tbh-capture.workspace = true
tbh-core.workspace = true
tbh-input.workspace = true
tbh-vision.workspace = true

[lints]
workspace = true
